spring:
  datasource:
    url: jdbc:mysql://localhost:3307/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-dev.yaml


server:
  port: 9003